/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  Alert as BlazeAlert
} from './components/alert/blaze-alert';

declare global {
  interface HTMLBlazeAlertElement extends BlazeAlert, HTMLElement {
  }
  var HTMLBlazeAlertElement: {
    prototype: HTMLBlazeAlertElement;
    new (): HTMLBlazeAlertElement;
  };
  interface HTMLElementTagNameMap {
    "blaze-alert": HTMLBlazeAlertElement;
  }
  interface ElementTagNameMap {
    "blaze-alert": HTMLBlazeAlertElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "blaze-alert": JSXElements.BlazeAlertAttributes;
    }
  }
  namespace JSXElements {
    export interface BlazeAlertAttributes extends HTMLAttributes {
      
        type?: string
    }
  }
}

