/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IAutoCompleteItem } from "./components/autocomplete/interfaces";
import { IOption } from "./components/tags/interfaces";
export namespace Components {
    interface BlazeAccordion {
    }
    interface BlazeAccordionPane {
        "close": () => Promise<void>;
        "header": string;
        "isOpen": () => Promise<boolean>;
        "open": boolean;
        "show": () => Promise<void>;
    }
    interface BlazeAddress {
    }
    interface BlazeAddressHeading {
    }
    interface BlazeAlert {
        "close": () => Promise<void>;
        "dismissible": boolean;
        "isOpen": () => Promise<boolean>;
        "open": boolean;
        "show": () => Promise<void>;
        "type": string;
    }
    interface BlazeAlerts {
        "position": string;
    }
    interface BlazeAutocomplete {
        "placeholder": string;
        "reset": () => Promise<void>;
        "setItems": (items: Array<IAutoCompleteItem>) => Promise<void>;
    }
    interface BlazeAvatar {
        "alt": string;
        "alt2": string;
        "size": string;
        "src": string;
        "src2": string;
        "text": string;
    }
    interface BlazeBackToTop {
        "position": string;
    }
    interface BlazeBadge {
        "ghost": boolean;
        "rounded": boolean;
        "type": string;
    }
    interface BlazeCalendar {
        "date": string;
        "multiple": boolean;
        "type": string;
    }
    interface BlazeCard {
    }
    interface BlazeCardBody {
    }
    interface BlazeCardFooter {
    }
    interface BlazeCardHeader {
    }
    interface BlazeCounter {
        "autoStart": boolean;
        "decimal": string;
        "decimals": number;
        "delay": number;
        "duration": number;
        "easing": boolean;
        "endValue": number;
        "grouping": boolean;
        "pauseResume": () => Promise<void>;
        "reset": () => Promise<void>;
        "restart": () => Promise<void>;
        "separator": string;
        "start": () => Promise<void>;
        "startValue": number;
        "update": (value: number) => Promise<void>;
    }
    interface BlazeDemo {
        "classes": string;
        "code": string;
        "demo": boolean;
        "language": string;
    }
    interface BlazeDivider {
        "type": string;
    }
    interface BlazeDrawer {
        "close": () => Promise<void>;
        "dismissible": boolean;
        "isOpen": () => Promise<boolean>;
        "open": boolean;
        "position": string;
        "shouldClose": () => boolean;
        "show": () => Promise<void>;
    }
    interface BlazeFileUpload {
        "drop": boolean;
        "multiple": boolean;
        "url": string;
    }
    interface BlazeImage {
        "alt": string;
        "collection": string;
        "filter": string;
        "height": number;
        "likes": boolean;
        "photo": string;
        "src": string;
        "user": string;
        "width": number;
    }
    interface BlazeMediaBody {
    }
    interface BlazeMediaImage {
        "alt": string;
        "src": string;
    }
    interface BlazeMediaItem {
    }
    interface BlazeModal {
        "close": () => Promise<void>;
        "dismissible": boolean;
        "full": boolean;
        "ghost": boolean;
        "isOpen": () => Promise<boolean>;
        "open": boolean;
        "shouldClose": () => boolean;
        "show": () => Promise<void>;
    }
    interface BlazePagination {
        "currentPage": () => Promise<number>;
        "goToPage": (page: number) => Promise<void>;
        "page": number;
        "pages": number;
    }
    interface BlazePanel {
        "height": number;
    }
    interface BlazeProgress {
        "rounded": boolean;
        "size": string;
        "timer": boolean;
    }
    interface BlazeProgressBar {
        "duration": number;
        "max": number;
        "min": number;
        "type": string;
        "value": number;
    }
    interface BlazeSticky {
        "top": number;
    }
    interface BlazeTab {
        "disabled": boolean;
        "header": string;
        "open": boolean;
        "type": string;
    }
    interface BlazeTabs {
        "currentTab": () => Promise<number>;
        "openTab": (tabIndex: number) => Promise<void>;
    }
    interface BlazeTags {
        "autocomplete": boolean;
        "options": string;
        "placeholder": string;
        "setOptions": (options?: Array<IOption>) => Promise<any>;
    }
    interface BlazeTimeline {
        "alternate": boolean;
        "loading": boolean;
    }
    interface BlazeTimelineItem {
        "last": boolean;
        "left": boolean;
        "loading": boolean;
        "type": string;
    }
    interface BlazeToggle {
        "isToggled": () => Promise<boolean>;
        "toggled": boolean;
        "type": string;
    }
    interface BlazeTree {
    }
    interface BlazeTreeBranch {
        "collapse": () => Promise<void>;
        "expand": () => Promise<void>;
    }
    interface BlazeTreeLeaf {
    }
}
export interface BlazeAccordionCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBlazeAccordionElement;
}
export interface BlazeAccordionPaneCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBlazeAccordionPaneElement;
}
export interface BlazeAlertCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBlazeAlertElement;
}
export interface BlazeAutocompleteCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBlazeAutocompleteElement;
}
export interface BlazeBackToTopCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBlazeBackToTopElement;
}
export interface BlazeCalendarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBlazeCalendarElement;
}
export interface BlazeCounterCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBlazeCounterElement;
}
export interface BlazeDrawerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBlazeDrawerElement;
}
export interface BlazeFileUploadCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBlazeFileUploadElement;
}
export interface BlazeModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBlazeModalElement;
}
export interface BlazePaginationCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBlazePaginationElement;
}
export interface BlazeProgressCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBlazeProgressElement;
}
export interface BlazeProgressBarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBlazeProgressBarElement;
}
export interface BlazeTabsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBlazeTabsElement;
}
export interface BlazeTagsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBlazeTagsElement;
}
export interface BlazeToggleCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBlazeToggleElement;
}
export interface BlazeTreeBranchCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBlazeTreeBranchElement;
}
declare global {
    interface HTMLBlazeAccordionElement extends Components.BlazeAccordion, HTMLStencilElement {
    }
    var HTMLBlazeAccordionElement: {
        prototype: HTMLBlazeAccordionElement;
        new (): HTMLBlazeAccordionElement;
    };
    interface HTMLBlazeAccordionPaneElement extends Components.BlazeAccordionPane, HTMLStencilElement {
    }
    var HTMLBlazeAccordionPaneElement: {
        prototype: HTMLBlazeAccordionPaneElement;
        new (): HTMLBlazeAccordionPaneElement;
    };
    interface HTMLBlazeAddressElement extends Components.BlazeAddress, HTMLStencilElement {
    }
    var HTMLBlazeAddressElement: {
        prototype: HTMLBlazeAddressElement;
        new (): HTMLBlazeAddressElement;
    };
    interface HTMLBlazeAddressHeadingElement extends Components.BlazeAddressHeading, HTMLStencilElement {
    }
    var HTMLBlazeAddressHeadingElement: {
        prototype: HTMLBlazeAddressHeadingElement;
        new (): HTMLBlazeAddressHeadingElement;
    };
    interface HTMLBlazeAlertElement extends Components.BlazeAlert, HTMLStencilElement {
    }
    var HTMLBlazeAlertElement: {
        prototype: HTMLBlazeAlertElement;
        new (): HTMLBlazeAlertElement;
    };
    interface HTMLBlazeAlertsElement extends Components.BlazeAlerts, HTMLStencilElement {
    }
    var HTMLBlazeAlertsElement: {
        prototype: HTMLBlazeAlertsElement;
        new (): HTMLBlazeAlertsElement;
    };
    interface HTMLBlazeAutocompleteElement extends Components.BlazeAutocomplete, HTMLStencilElement {
    }
    var HTMLBlazeAutocompleteElement: {
        prototype: HTMLBlazeAutocompleteElement;
        new (): HTMLBlazeAutocompleteElement;
    };
    interface HTMLBlazeAvatarElement extends Components.BlazeAvatar, HTMLStencilElement {
    }
    var HTMLBlazeAvatarElement: {
        prototype: HTMLBlazeAvatarElement;
        new (): HTMLBlazeAvatarElement;
    };
    interface HTMLBlazeBackToTopElement extends Components.BlazeBackToTop, HTMLStencilElement {
    }
    var HTMLBlazeBackToTopElement: {
        prototype: HTMLBlazeBackToTopElement;
        new (): HTMLBlazeBackToTopElement;
    };
    interface HTMLBlazeBadgeElement extends Components.BlazeBadge, HTMLStencilElement {
    }
    var HTMLBlazeBadgeElement: {
        prototype: HTMLBlazeBadgeElement;
        new (): HTMLBlazeBadgeElement;
    };
    interface HTMLBlazeCalendarElement extends Components.BlazeCalendar, HTMLStencilElement {
    }
    var HTMLBlazeCalendarElement: {
        prototype: HTMLBlazeCalendarElement;
        new (): HTMLBlazeCalendarElement;
    };
    interface HTMLBlazeCardElement extends Components.BlazeCard, HTMLStencilElement {
    }
    var HTMLBlazeCardElement: {
        prototype: HTMLBlazeCardElement;
        new (): HTMLBlazeCardElement;
    };
    interface HTMLBlazeCardBodyElement extends Components.BlazeCardBody, HTMLStencilElement {
    }
    var HTMLBlazeCardBodyElement: {
        prototype: HTMLBlazeCardBodyElement;
        new (): HTMLBlazeCardBodyElement;
    };
    interface HTMLBlazeCardFooterElement extends Components.BlazeCardFooter, HTMLStencilElement {
    }
    var HTMLBlazeCardFooterElement: {
        prototype: HTMLBlazeCardFooterElement;
        new (): HTMLBlazeCardFooterElement;
    };
    interface HTMLBlazeCardHeaderElement extends Components.BlazeCardHeader, HTMLStencilElement {
    }
    var HTMLBlazeCardHeaderElement: {
        prototype: HTMLBlazeCardHeaderElement;
        new (): HTMLBlazeCardHeaderElement;
    };
    interface HTMLBlazeCounterElement extends Components.BlazeCounter, HTMLStencilElement {
    }
    var HTMLBlazeCounterElement: {
        prototype: HTMLBlazeCounterElement;
        new (): HTMLBlazeCounterElement;
    };
    interface HTMLBlazeDemoElement extends Components.BlazeDemo, HTMLStencilElement {
    }
    var HTMLBlazeDemoElement: {
        prototype: HTMLBlazeDemoElement;
        new (): HTMLBlazeDemoElement;
    };
    interface HTMLBlazeDividerElement extends Components.BlazeDivider, HTMLStencilElement {
    }
    var HTMLBlazeDividerElement: {
        prototype: HTMLBlazeDividerElement;
        new (): HTMLBlazeDividerElement;
    };
    interface HTMLBlazeDrawerElement extends Components.BlazeDrawer, HTMLStencilElement {
    }
    var HTMLBlazeDrawerElement: {
        prototype: HTMLBlazeDrawerElement;
        new (): HTMLBlazeDrawerElement;
    };
    interface HTMLBlazeFileUploadElement extends Components.BlazeFileUpload, HTMLStencilElement {
    }
    var HTMLBlazeFileUploadElement: {
        prototype: HTMLBlazeFileUploadElement;
        new (): HTMLBlazeFileUploadElement;
    };
    interface HTMLBlazeImageElement extends Components.BlazeImage, HTMLStencilElement {
    }
    var HTMLBlazeImageElement: {
        prototype: HTMLBlazeImageElement;
        new (): HTMLBlazeImageElement;
    };
    interface HTMLBlazeMediaBodyElement extends Components.BlazeMediaBody, HTMLStencilElement {
    }
    var HTMLBlazeMediaBodyElement: {
        prototype: HTMLBlazeMediaBodyElement;
        new (): HTMLBlazeMediaBodyElement;
    };
    interface HTMLBlazeMediaImageElement extends Components.BlazeMediaImage, HTMLStencilElement {
    }
    var HTMLBlazeMediaImageElement: {
        prototype: HTMLBlazeMediaImageElement;
        new (): HTMLBlazeMediaImageElement;
    };
    interface HTMLBlazeMediaItemElement extends Components.BlazeMediaItem, HTMLStencilElement {
    }
    var HTMLBlazeMediaItemElement: {
        prototype: HTMLBlazeMediaItemElement;
        new (): HTMLBlazeMediaItemElement;
    };
    interface HTMLBlazeModalElement extends Components.BlazeModal, HTMLStencilElement {
    }
    var HTMLBlazeModalElement: {
        prototype: HTMLBlazeModalElement;
        new (): HTMLBlazeModalElement;
    };
    interface HTMLBlazePaginationElement extends Components.BlazePagination, HTMLStencilElement {
    }
    var HTMLBlazePaginationElement: {
        prototype: HTMLBlazePaginationElement;
        new (): HTMLBlazePaginationElement;
    };
    interface HTMLBlazePanelElement extends Components.BlazePanel, HTMLStencilElement {
    }
    var HTMLBlazePanelElement: {
        prototype: HTMLBlazePanelElement;
        new (): HTMLBlazePanelElement;
    };
    interface HTMLBlazeProgressElement extends Components.BlazeProgress, HTMLStencilElement {
    }
    var HTMLBlazeProgressElement: {
        prototype: HTMLBlazeProgressElement;
        new (): HTMLBlazeProgressElement;
    };
    interface HTMLBlazeProgressBarElement extends Components.BlazeProgressBar, HTMLStencilElement {
    }
    var HTMLBlazeProgressBarElement: {
        prototype: HTMLBlazeProgressBarElement;
        new (): HTMLBlazeProgressBarElement;
    };
    interface HTMLBlazeStickyElement extends Components.BlazeSticky, HTMLStencilElement {
    }
    var HTMLBlazeStickyElement: {
        prototype: HTMLBlazeStickyElement;
        new (): HTMLBlazeStickyElement;
    };
    interface HTMLBlazeTabElement extends Components.BlazeTab, HTMLStencilElement {
    }
    var HTMLBlazeTabElement: {
        prototype: HTMLBlazeTabElement;
        new (): HTMLBlazeTabElement;
    };
    interface HTMLBlazeTabsElement extends Components.BlazeTabs, HTMLStencilElement {
    }
    var HTMLBlazeTabsElement: {
        prototype: HTMLBlazeTabsElement;
        new (): HTMLBlazeTabsElement;
    };
    interface HTMLBlazeTagsElement extends Components.BlazeTags, HTMLStencilElement {
    }
    var HTMLBlazeTagsElement: {
        prototype: HTMLBlazeTagsElement;
        new (): HTMLBlazeTagsElement;
    };
    interface HTMLBlazeTimelineElement extends Components.BlazeTimeline, HTMLStencilElement {
    }
    var HTMLBlazeTimelineElement: {
        prototype: HTMLBlazeTimelineElement;
        new (): HTMLBlazeTimelineElement;
    };
    interface HTMLBlazeTimelineItemElement extends Components.BlazeTimelineItem, HTMLStencilElement {
    }
    var HTMLBlazeTimelineItemElement: {
        prototype: HTMLBlazeTimelineItemElement;
        new (): HTMLBlazeTimelineItemElement;
    };
    interface HTMLBlazeToggleElement extends Components.BlazeToggle, HTMLStencilElement {
    }
    var HTMLBlazeToggleElement: {
        prototype: HTMLBlazeToggleElement;
        new (): HTMLBlazeToggleElement;
    };
    interface HTMLBlazeTreeElement extends Components.BlazeTree, HTMLStencilElement {
    }
    var HTMLBlazeTreeElement: {
        prototype: HTMLBlazeTreeElement;
        new (): HTMLBlazeTreeElement;
    };
    interface HTMLBlazeTreeBranchElement extends Components.BlazeTreeBranch, HTMLStencilElement {
    }
    var HTMLBlazeTreeBranchElement: {
        prototype: HTMLBlazeTreeBranchElement;
        new (): HTMLBlazeTreeBranchElement;
    };
    interface HTMLBlazeTreeLeafElement extends Components.BlazeTreeLeaf, HTMLStencilElement {
    }
    var HTMLBlazeTreeLeafElement: {
        prototype: HTMLBlazeTreeLeafElement;
        new (): HTMLBlazeTreeLeafElement;
    };
    interface HTMLElementTagNameMap {
        "blaze-accordion": HTMLBlazeAccordionElement;
        "blaze-accordion-pane": HTMLBlazeAccordionPaneElement;
        "blaze-address": HTMLBlazeAddressElement;
        "blaze-address-heading": HTMLBlazeAddressHeadingElement;
        "blaze-alert": HTMLBlazeAlertElement;
        "blaze-alerts": HTMLBlazeAlertsElement;
        "blaze-autocomplete": HTMLBlazeAutocompleteElement;
        "blaze-avatar": HTMLBlazeAvatarElement;
        "blaze-back-to-top": HTMLBlazeBackToTopElement;
        "blaze-badge": HTMLBlazeBadgeElement;
        "blaze-calendar": HTMLBlazeCalendarElement;
        "blaze-card": HTMLBlazeCardElement;
        "blaze-card-body": HTMLBlazeCardBodyElement;
        "blaze-card-footer": HTMLBlazeCardFooterElement;
        "blaze-card-header": HTMLBlazeCardHeaderElement;
        "blaze-counter": HTMLBlazeCounterElement;
        "blaze-demo": HTMLBlazeDemoElement;
        "blaze-divider": HTMLBlazeDividerElement;
        "blaze-drawer": HTMLBlazeDrawerElement;
        "blaze-file-upload": HTMLBlazeFileUploadElement;
        "blaze-image": HTMLBlazeImageElement;
        "blaze-media-body": HTMLBlazeMediaBodyElement;
        "blaze-media-image": HTMLBlazeMediaImageElement;
        "blaze-media-item": HTMLBlazeMediaItemElement;
        "blaze-modal": HTMLBlazeModalElement;
        "blaze-pagination": HTMLBlazePaginationElement;
        "blaze-panel": HTMLBlazePanelElement;
        "blaze-progress": HTMLBlazeProgressElement;
        "blaze-progress-bar": HTMLBlazeProgressBarElement;
        "blaze-sticky": HTMLBlazeStickyElement;
        "blaze-tab": HTMLBlazeTabElement;
        "blaze-tabs": HTMLBlazeTabsElement;
        "blaze-tags": HTMLBlazeTagsElement;
        "blaze-timeline": HTMLBlazeTimelineElement;
        "blaze-timeline-item": HTMLBlazeTimelineItemElement;
        "blaze-toggle": HTMLBlazeToggleElement;
        "blaze-tree": HTMLBlazeTreeElement;
        "blaze-tree-branch": HTMLBlazeTreeBranchElement;
        "blaze-tree-leaf": HTMLBlazeTreeLeafElement;
    }
}
declare namespace LocalJSX {
    interface BlazeAccordion {
        "onToggle"?: (event: BlazeAccordionCustomEvent<any>) => void;
    }
    interface BlazeAccordionPane {
        "header"?: string;
        "onTogglepane"?: (event: BlazeAccordionPaneCustomEvent<any>) => void;
        "open"?: boolean;
    }
    interface BlazeAddress {
    }
    interface BlazeAddressHeading {
    }
    interface BlazeAlert {
        "dismissible"?: boolean;
        "onClose"?: (event: BlazeAlertCustomEvent<any>) => void;
        "open"?: boolean;
        "type"?: string;
    }
    interface BlazeAlerts {
        "position"?: string;
    }
    interface BlazeAutocomplete {
        "onFilter"?: (event: BlazeAutocompleteCustomEvent<any>) => void;
        "onSelected"?: (event: BlazeAutocompleteCustomEvent<any>) => void;
        "placeholder"?: string;
    }
    interface BlazeAvatar {
        "alt"?: string;
        "alt2"?: string;
        "size"?: string;
        "src"?: string;
        "src2"?: string;
        "text"?: string;
    }
    interface BlazeBackToTop {
        "onBacktotop"?: (event: BlazeBackToTopCustomEvent<any>) => void;
        "position"?: string;
    }
    interface BlazeBadge {
        "ghost"?: boolean;
        "rounded"?: boolean;
        "type"?: string;
    }
    interface BlazeCalendar {
        "date"?: string;
        "multiple"?: boolean;
        "onSelected"?: (event: BlazeCalendarCustomEvent<any>) => void;
        "type"?: string;
    }
    interface BlazeCard {
    }
    interface BlazeCardBody {
    }
    interface BlazeCardFooter {
    }
    interface BlazeCardHeader {
    }
    interface BlazeCounter {
        "autoStart"?: boolean;
        "decimal"?: string;
        "decimals"?: number;
        "delay"?: number;
        "duration"?: number;
        "easing"?: boolean;
        "endValue"?: number;
        "grouping"?: boolean;
        "onFinish"?: (event: BlazeCounterCustomEvent<any>) => void;
        "separator"?: string;
        "startValue"?: number;
    }
    interface BlazeDemo {
        "classes"?: string;
        "code"?: string;
        "demo"?: boolean;
        "language"?: string;
    }
    interface BlazeDivider {
        "type"?: string;
    }
    interface BlazeDrawer {
        "dismissible"?: boolean;
        "onClose"?: (event: BlazeDrawerCustomEvent<any>) => void;
        "open"?: boolean;
        "position"?: string;
        "shouldClose"?: () => boolean;
    }
    interface BlazeFileUpload {
        "drop"?: boolean;
        "multiple"?: boolean;
        "onUploaded"?: (event: BlazeFileUploadCustomEvent<any>) => void;
        "onUploading"?: (event: BlazeFileUploadCustomEvent<any>) => void;
        "url"?: string;
    }
    interface BlazeImage {
        "alt"?: string;
        "collection"?: string;
        "filter"?: string;
        "height"?: number;
        "likes"?: boolean;
        "photo"?: string;
        "src"?: string;
        "user"?: string;
        "width"?: number;
    }
    interface BlazeMediaBody {
    }
    interface BlazeMediaImage {
        "alt"?: string;
        "src"?: string;
    }
    interface BlazeMediaItem {
    }
    interface BlazeModal {
        "dismissible"?: boolean;
        "full"?: boolean;
        "ghost"?: boolean;
        "onClose"?: (event: BlazeModalCustomEvent<any>) => void;
        "open"?: boolean;
        "shouldClose"?: () => boolean;
    }
    interface BlazePagination {
        "onPage"?: (event: BlazePaginationCustomEvent<any>) => void;
        "page"?: number;
        "pages"?: number;
    }
    interface BlazePanel {
        "height"?: number;
    }
    interface BlazeProgress {
        "onChanged"?: (event: BlazeProgressCustomEvent<any>) => void;
        "rounded"?: boolean;
        "size"?: string;
        "timer"?: boolean;
    }
    interface BlazeProgressBar {
        "duration"?: number;
        "max"?: number;
        "min"?: number;
        "onProgressbar"?: (event: BlazeProgressBarCustomEvent<any>) => void;
        "type"?: string;
        "value"?: number;
    }
    interface BlazeSticky {
        "top"?: number;
    }
    interface BlazeTab {
        "disabled"?: boolean;
        "header"?: string;
        "open"?: boolean;
        "type"?: string;
    }
    interface BlazeTabs {
        "onTab"?: (event: BlazeTabsCustomEvent<any>) => void;
    }
    interface BlazeTags {
        "autocomplete"?: boolean;
        "onAdd"?: (event: BlazeTagsCustomEvent<any>) => void;
        "onFilter"?: (event: BlazeTagsCustomEvent<any>) => void;
        "options"?: string;
        "placeholder"?: string;
    }
    interface BlazeTimeline {
        "alternate"?: boolean;
        "loading"?: boolean;
    }
    interface BlazeTimelineItem {
        "last"?: boolean;
        "left"?: boolean;
        "loading"?: boolean;
        "type"?: string;
    }
    interface BlazeToggle {
        "onToggle"?: (event: BlazeToggleCustomEvent<any>) => void;
        "toggled"?: boolean;
        "type"?: string;
    }
    interface BlazeTree {
    }
    interface BlazeTreeBranch {
        "onCollapse"?: (event: BlazeTreeBranchCustomEvent<any>) => void;
        "onExpand"?: (event: BlazeTreeBranchCustomEvent<any>) => void;
    }
    interface BlazeTreeLeaf {
    }
    interface IntrinsicElements {
        "blaze-accordion": BlazeAccordion;
        "blaze-accordion-pane": BlazeAccordionPane;
        "blaze-address": BlazeAddress;
        "blaze-address-heading": BlazeAddressHeading;
        "blaze-alert": BlazeAlert;
        "blaze-alerts": BlazeAlerts;
        "blaze-autocomplete": BlazeAutocomplete;
        "blaze-avatar": BlazeAvatar;
        "blaze-back-to-top": BlazeBackToTop;
        "blaze-badge": BlazeBadge;
        "blaze-calendar": BlazeCalendar;
        "blaze-card": BlazeCard;
        "blaze-card-body": BlazeCardBody;
        "blaze-card-footer": BlazeCardFooter;
        "blaze-card-header": BlazeCardHeader;
        "blaze-counter": BlazeCounter;
        "blaze-demo": BlazeDemo;
        "blaze-divider": BlazeDivider;
        "blaze-drawer": BlazeDrawer;
        "blaze-file-upload": BlazeFileUpload;
        "blaze-image": BlazeImage;
        "blaze-media-body": BlazeMediaBody;
        "blaze-media-image": BlazeMediaImage;
        "blaze-media-item": BlazeMediaItem;
        "blaze-modal": BlazeModal;
        "blaze-pagination": BlazePagination;
        "blaze-panel": BlazePanel;
        "blaze-progress": BlazeProgress;
        "blaze-progress-bar": BlazeProgressBar;
        "blaze-sticky": BlazeSticky;
        "blaze-tab": BlazeTab;
        "blaze-tabs": BlazeTabs;
        "blaze-tags": BlazeTags;
        "blaze-timeline": BlazeTimeline;
        "blaze-timeline-item": BlazeTimelineItem;
        "blaze-toggle": BlazeToggle;
        "blaze-tree": BlazeTree;
        "blaze-tree-branch": BlazeTreeBranch;
        "blaze-tree-leaf": BlazeTreeLeaf;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "blaze-accordion": LocalJSX.BlazeAccordion & JSXBase.HTMLAttributes<HTMLBlazeAccordionElement>;
            "blaze-accordion-pane": LocalJSX.BlazeAccordionPane & JSXBase.HTMLAttributes<HTMLBlazeAccordionPaneElement>;
            "blaze-address": LocalJSX.BlazeAddress & JSXBase.HTMLAttributes<HTMLBlazeAddressElement>;
            "blaze-address-heading": LocalJSX.BlazeAddressHeading & JSXBase.HTMLAttributes<HTMLBlazeAddressHeadingElement>;
            "blaze-alert": LocalJSX.BlazeAlert & JSXBase.HTMLAttributes<HTMLBlazeAlertElement>;
            "blaze-alerts": LocalJSX.BlazeAlerts & JSXBase.HTMLAttributes<HTMLBlazeAlertsElement>;
            "blaze-autocomplete": LocalJSX.BlazeAutocomplete & JSXBase.HTMLAttributes<HTMLBlazeAutocompleteElement>;
            "blaze-avatar": LocalJSX.BlazeAvatar & JSXBase.HTMLAttributes<HTMLBlazeAvatarElement>;
            "blaze-back-to-top": LocalJSX.BlazeBackToTop & JSXBase.HTMLAttributes<HTMLBlazeBackToTopElement>;
            "blaze-badge": LocalJSX.BlazeBadge & JSXBase.HTMLAttributes<HTMLBlazeBadgeElement>;
            "blaze-calendar": LocalJSX.BlazeCalendar & JSXBase.HTMLAttributes<HTMLBlazeCalendarElement>;
            "blaze-card": LocalJSX.BlazeCard & JSXBase.HTMLAttributes<HTMLBlazeCardElement>;
            "blaze-card-body": LocalJSX.BlazeCardBody & JSXBase.HTMLAttributes<HTMLBlazeCardBodyElement>;
            "blaze-card-footer": LocalJSX.BlazeCardFooter & JSXBase.HTMLAttributes<HTMLBlazeCardFooterElement>;
            "blaze-card-header": LocalJSX.BlazeCardHeader & JSXBase.HTMLAttributes<HTMLBlazeCardHeaderElement>;
            "blaze-counter": LocalJSX.BlazeCounter & JSXBase.HTMLAttributes<HTMLBlazeCounterElement>;
            "blaze-demo": LocalJSX.BlazeDemo & JSXBase.HTMLAttributes<HTMLBlazeDemoElement>;
            "blaze-divider": LocalJSX.BlazeDivider & JSXBase.HTMLAttributes<HTMLBlazeDividerElement>;
            "blaze-drawer": LocalJSX.BlazeDrawer & JSXBase.HTMLAttributes<HTMLBlazeDrawerElement>;
            "blaze-file-upload": LocalJSX.BlazeFileUpload & JSXBase.HTMLAttributes<HTMLBlazeFileUploadElement>;
            "blaze-image": LocalJSX.BlazeImage & JSXBase.HTMLAttributes<HTMLBlazeImageElement>;
            "blaze-media-body": LocalJSX.BlazeMediaBody & JSXBase.HTMLAttributes<HTMLBlazeMediaBodyElement>;
            "blaze-media-image": LocalJSX.BlazeMediaImage & JSXBase.HTMLAttributes<HTMLBlazeMediaImageElement>;
            "blaze-media-item": LocalJSX.BlazeMediaItem & JSXBase.HTMLAttributes<HTMLBlazeMediaItemElement>;
            "blaze-modal": LocalJSX.BlazeModal & JSXBase.HTMLAttributes<HTMLBlazeModalElement>;
            "blaze-pagination": LocalJSX.BlazePagination & JSXBase.HTMLAttributes<HTMLBlazePaginationElement>;
            "blaze-panel": LocalJSX.BlazePanel & JSXBase.HTMLAttributes<HTMLBlazePanelElement>;
            "blaze-progress": LocalJSX.BlazeProgress & JSXBase.HTMLAttributes<HTMLBlazeProgressElement>;
            "blaze-progress-bar": LocalJSX.BlazeProgressBar & JSXBase.HTMLAttributes<HTMLBlazeProgressBarElement>;
            "blaze-sticky": LocalJSX.BlazeSticky & JSXBase.HTMLAttributes<HTMLBlazeStickyElement>;
            "blaze-tab": LocalJSX.BlazeTab & JSXBase.HTMLAttributes<HTMLBlazeTabElement>;
            "blaze-tabs": LocalJSX.BlazeTabs & JSXBase.HTMLAttributes<HTMLBlazeTabsElement>;
            "blaze-tags": LocalJSX.BlazeTags & JSXBase.HTMLAttributes<HTMLBlazeTagsElement>;
            "blaze-timeline": LocalJSX.BlazeTimeline & JSXBase.HTMLAttributes<HTMLBlazeTimelineElement>;
            "blaze-timeline-item": LocalJSX.BlazeTimelineItem & JSXBase.HTMLAttributes<HTMLBlazeTimelineItemElement>;
            "blaze-toggle": LocalJSX.BlazeToggle & JSXBase.HTMLAttributes<HTMLBlazeToggleElement>;
            "blaze-tree": LocalJSX.BlazeTree & JSXBase.HTMLAttributes<HTMLBlazeTreeElement>;
            "blaze-tree-branch": LocalJSX.BlazeTreeBranch & JSXBase.HTMLAttributes<HTMLBlazeTreeBranchElement>;
            "blaze-tree-leaf": LocalJSX.BlazeTreeLeaf & JSXBase.HTMLAttributes<HTMLBlazeTreeLeafElement>;
        }
    }
}
